-- =================================================================
-- SMART AGROMART - SUPABASE POSTGRESQL SCHEMA & RPC TRANSACTIONS
-- Production Hardened, RLS Secured, Exact Accounting Reconciliation & Idempotent
-- =================================================================

-- 1. EXTENSIONS & SEQUENCES
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE SEQUENCE IF NOT EXISTS invoice_number_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS payment_number_seq START WITH 1;
CREATE SEQUENCE IF NOT EXISTS purchase_number_seq START WITH 1;

-- 2. SCHEMA & TABLE PERMISSIONS
GRANT USAGE ON SCHEMA public TO authenticated, anon;

-- 3. TABLES WITH HARDENED CONSTRAINTS & HISTORICAL DATA PROTECTION

-- Profiles (linked to auth.users)
CREATE TABLE IF NOT EXISTS profiles (
    id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    role TEXT NOT NULL DEFAULT 'Staff', -- Admin, Staff, Accountant
    avatar_url TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Farmers (RESTRICT deletion if credit transactions exist; NOT NULL Credit Defaults)
CREATE TABLE IF NOT EXISTS farmers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    mobile TEXT UNIQUE NOT NULL,
    village TEXT,
    district TEXT,
    land_acreage NUMERIC(10, 2) NOT NULL DEFAULT 0.0 CHECK (land_acreage >= 0),
    primary_crop TEXT,
    pending_credit NUMERIC(12, 2) NOT NULL DEFAULT 0.0 CHECK (pending_credit >= 0),
    credit_limit NUMERIC(12, 2) NOT NULL DEFAULT 50000.0 CHECK (credit_limit >= 0),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Suppliers
CREATE TABLE IF NOT EXISTS suppliers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    company_name TEXT,
    contact_person TEXT,
    mobile TEXT,
    email TEXT,
    gstin TEXT,
    pan TEXT,
    address TEXT,
    city TEXT,
    district TEXT,
    state TEXT,
    pincode TEXT,
    total_purchases NUMERIC(12, 2) NOT NULL DEFAULT 0.0 CHECK (total_purchases >= 0),
    pending_payment NUMERIC(12, 2) NOT NULL DEFAULT 0.0 CHECK (pending_payment >= 0),
    pending_payable NUMERIC(12, 2) NOT NULL DEFAULT 0.0 CHECK (pending_payable >= 0),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);


-- Categories
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Products (total_stock is explicitly cached/derived summary data from product_batches)
CREATE TABLE IF NOT EXISTS products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_code TEXT UNIQUE NOT NULL,
    name TEXT NOT NULL,
    category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
    brand TEXT,
    composition TEXT,
    hsn_code TEXT DEFAULT '3105',
    unit TEXT DEFAULT 'Bags',
    gst_percent NUMERIC(5, 2) DEFAULT 5.0 CHECK (gst_percent >= 0 AND gst_percent <= 100),
    purchase_price NUMERIC(12, 2) NOT NULL CHECK (purchase_price >= 0),
    selling_price NUMERIC(12, 2) NOT NULL CHECK (selling_price >= 0),
    min_stock_alert INT DEFAULT 10 CHECK (min_stock_alert >= 0),
    total_stock INT DEFAULT 0 CHECK (total_stock >= 0),
    status TEXT DEFAULT 'Active',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Product Batches (Authoritative Stock Source of Truth)
CREATE TABLE IF NOT EXISTS product_batches (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    batch_number TEXT NOT NULL,
    mfg_date DATE,
    expiry_date DATE,
    initial_quantity INT DEFAULT 0 CHECK (initial_quantity >= 0),
    current_quantity INT DEFAULT 0 CHECK (current_quantity >= 0),
    purchase_price NUMERIC(12, 2) NOT NULL CHECK (purchase_price >= 0),
    selling_price NUMERIC(12, 2) NOT NULL CHECK (selling_price >= 0),
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT unique_product_batch UNIQUE (product_id, batch_number)
);

-- Stock Movements (Financial/Stock Audit Log - Direct writes prohibited)
CREATE TABLE IF NOT EXISTS stock_movements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    batch_id BIGINT REFERENCES product_batches(id) ON DELETE SET NULL,
    movement_type TEXT NOT NULL, -- SALE, INWARD, ADJUSTMENT_ADD, ADJUSTMENT_REDUCE, RETURN
    quantity INT NOT NULL CHECK (quantity > 0),
    reference_type TEXT, -- BILL, PURCHASE, MANUAL
    reference_id TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Purchases
CREATE TABLE IF NOT EXISTS purchases (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_number TEXT UNIQUE NOT NULL,
    purchase_date TIMESTAMPTZ DEFAULT NOW(),
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    supplier_name TEXT NOT NULL,
    subtotal NUMERIC(12, 2) DEFAULT 0.0 CHECK (subtotal >= 0),
    gst_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (gst_amount >= 0),
    grand_total NUMERIC(12, 2) DEFAULT 0.0 CHECK (grand_total >= 0),
    paid_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (paid_amount >= 0),
    pending_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (pending_amount >= 0),
    payment_status TEXT DEFAULT 'Paid',
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Purchase Items
CREATE TABLE IF NOT EXISTS purchase_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    purchase_id BIGINT NOT NULL REFERENCES purchases(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    batch_id BIGINT REFERENCES product_batches(id) ON DELETE SET NULL,
    quantity INT NOT NULL CHECK (quantity > 0),
    purchase_price NUMERIC(12, 2) NOT NULL CHECK (purchase_price >= 0),
    gst_percent NUMERIC(5, 2) DEFAULT 5.0 CHECK (gst_percent >= 0 AND gst_percent <= 100),
    taxable_amount NUMERIC(12, 2) NOT NULL CHECK (taxable_amount >= 0),
    gst_amount NUMERIC(12, 2) NOT NULL CHECK (gst_amount >= 0),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0)
);

-- Bills (Financial Audit Header - Direct writes prohibited)
CREATE TABLE IF NOT EXISTS bills (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_number TEXT UNIQUE NOT NULL,
    invoice_date TIMESTAMPTZ DEFAULT NOW(),
    farmer_id BIGINT REFERENCES farmers(id) ON DELETE SET NULL,
    farmer_name TEXT NOT NULL DEFAULT 'Walk-in Customer',
    farmer_mobile TEXT,
    subtotal NUMERIC(12, 2) DEFAULT 0.0 CHECK (subtotal >= 0),
    taxable_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (taxable_amount >= 0),
    gst_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (gst_amount >= 0),
    cgst NUMERIC(12, 2) DEFAULT 0.0 CHECK (cgst >= 0),
    sgst NUMERIC(12, 2) DEFAULT 0.0 CHECK (sgst >= 0),
    igst NUMERIC(12, 2) DEFAULT 0.0 CHECK (igst >= 0),
    discount_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (discount_amount >= 0),
    grand_total NUMERIC(12, 2) DEFAULT 0.0 CHECK (grand_total >= 0),
    paid_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (paid_amount >= 0),
    pending_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (pending_amount >= 0),
    payment_method TEXT DEFAULT 'Cash',
    payment_status TEXT DEFAULT 'Paid',
    due_date TIMESTAMPTZ,
    notes TEXT,
    created_by UUID REFERENCES profiles(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Bill Items (Financial Audit Detail - Direct writes prohibited)
CREATE TABLE IF NOT EXISTS bill_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bill_id BIGINT NOT NULL REFERENCES bills(id) ON DELETE CASCADE,
    product_id BIGINT NOT NULL REFERENCES products(id) ON DELETE RESTRICT,
    batch_id BIGINT REFERENCES product_batches(id) ON DELETE SET NULL,
    product_name TEXT NOT NULL,
    batch_number TEXT,
    unit TEXT DEFAULT 'Bags',
    hsn_code TEXT DEFAULT '3105',
    quantity INT NOT NULL CHECK (quantity > 0),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    rate NUMERIC(12, 2) NOT NULL CHECK (rate >= 0),
    gst_percent NUMERIC(5, 2) DEFAULT 5.0 CHECK (gst_percent >= 0 AND gst_percent <= 100),
    discount_amount NUMERIC(12, 2) DEFAULT 0.0 CHECK (discount_amount >= 0),
    taxable_amount NUMERIC(12, 2) NOT NULL CHECK (taxable_amount >= 0),
    gst_amount NUMERIC(12, 2) NOT NULL CHECK (gst_amount >= 0),
    cgst NUMERIC(12, 2) DEFAULT 0.0 CHECK (cgst >= 0),
    sgst NUMERIC(12, 2) DEFAULT 0.0 CHECK (sgst >= 0),
    igst NUMERIC(12, 2) DEFAULT 0.0 CHECK (igst >= 0),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0)
);

-- Payments (Financial Audit - Direct writes prohibited)
CREATE TABLE IF NOT EXISTS payments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    payment_number TEXT UNIQUE NOT NULL,
    farmer_id BIGINT REFERENCES farmers(id) ON DELETE SET NULL,
    supplier_id BIGINT REFERENCES suppliers(id) ON DELETE SET NULL,
    bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    purchase_id BIGINT REFERENCES purchases(id) ON DELETE SET NULL,
    payment_type TEXT NOT NULL, -- BILL_PAYMENT, FARMER_CREDIT_REPAYMENT, SUPPLIER_PAYMENT
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    payment_method TEXT DEFAULT 'Cash',
    reference_number TEXT,
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Credit Transactions (Financial Ledger - RESTRICT farmer deletion to preserve audit history)
CREATE TABLE IF NOT EXISTS credit_transactions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    farmer_id BIGINT NOT NULL REFERENCES farmers(id) ON DELETE RESTRICT,
    bill_id BIGINT REFERENCES bills(id) ON DELETE SET NULL,
    payment_id BIGINT REFERENCES payments(id) ON DELETE SET NULL,
    transaction_type TEXT NOT NULL, -- DEBIT (Credit Taken), CREDIT (Payment Received)
    amount NUMERIC(12, 2) NOT NULL CHECK (amount > 0),
    balance_after NUMERIC(12, 2) NOT NULL CHECK (balance_after >= 0),
    notes TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Notifications
CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    message TEXT NOT NULL,
    category TEXT NOT NULL, -- STOCK, EXPIRY, CREDIT, SYSTEM
    severity TEXT DEFAULT 'info', -- info, warning, critical
    is_read BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- App Settings
CREATE TABLE IF NOT EXISTS app_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. INDEXES FOR PERFORMANCE
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_batches_product_exp ON product_batches(product_id, expiry_date);
CREATE INDEX IF NOT EXISTS idx_bills_farmer ON bills(farmer_id);
CREATE INDEX IF NOT EXISTS idx_bills_inv_num ON bills(invoice_number);
CREATE INDEX IF NOT EXISTS idx_credit_farmer ON credit_transactions(farmer_id);

-- 5. PROFILE AUTO-PROVISIONING TRIGGER ON auth.users
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
    INSERT INTO public.profiles (id, name, email, role, avatar_url)
    VALUES (
        NEW.id,
        COALESCE(NEW.raw_user_meta_data->>'name', NEW.raw_user_meta_data->>'full_name', SPLIT_PART(NEW.email, '@', 1)),
        NEW.email,
        'Staff',
        NEW.raw_user_meta_data->>'avatar_url'
    )
    ON CONFLICT (id) DO UPDATE SET
        name = EXCLUDED.name,
        email = EXCLUDED.email,
        updated_at = NOW();
    RETURN NEW;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.handle_new_user() FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.handle_new_user() TO authenticated;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
    AFTER INSERT ON auth.users
    FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- 6. EXPLICIT SQL DATA API GRANTS (Direct Mutations vs Financial RPC Protection)

-- Grant operational CRUD access to master/business data tables
GRANT SELECT, INSERT, UPDATE, DELETE ON farmers, suppliers, categories, products, product_batches, purchases, purchase_items, notifications, app_settings TO authenticated, anon;
GRANT SELECT, UPDATE ON profiles TO authenticated, anon;

-- Protect financial & stock transaction audit tables: Grant SELECT only (Direct INSERT/UPDATE/DELETE prohibited!)
GRANT SELECT ON bills, bill_items, payments, credit_transactions, stock_movements TO authenticated, anon;
REVOKE INSERT, UPDATE, DELETE ON bills, bill_items, payments, credit_transactions, stock_movements FROM authenticated, anon, PUBLIC;

-- Grant Sequence Usage for operational identity columns
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon;

-- 7. ROW LEVEL SECURITY (RLS) POLICIES (Idempotent & Authenticated Only)
-- TODO: Current authenticated master-data CRUD policies allow general authenticated users.
-- In a future role-hardening pass, restrict write policies based on profiles.role
-- (e.g. Admin, Staff, Accountant) to enforce fine-grained role permissions.

ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE farmers ENABLE ROW LEVEL SECURITY;
ALTER TABLE suppliers ENABLE ROW LEVEL SECURITY;
ALTER TABLE categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
ALTER TABLE product_batches ENABLE ROW LEVEL SECURITY;
ALTER TABLE stock_movements ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchases ENABLE ROW LEVEL SECURITY;
ALTER TABLE purchase_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE bills ENABLE ROW LEVEL SECURITY;
ALTER TABLE bill_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;
ALTER TABLE credit_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_settings ENABLE ROW LEVEL SECURITY;

-- Drop all policies for idempotent execution
DROP POLICY IF EXISTS "Auth users farmers access" ON farmers;
DROP POLICY IF EXISTS "Auth users products access" ON products;
DROP POLICY IF EXISTS "Auth users batches access" ON product_batches;
DROP POLICY IF EXISTS "Auth users bills select" ON bills;
DROP POLICY IF EXISTS "Auth users bill_items select" ON bill_items;
DROP POLICY IF EXISTS "Auth users movements select" ON stock_movements;
DROP POLICY IF EXISTS "Auth users payments select" ON payments;
DROP POLICY IF EXISTS "Auth users credit select" ON credit_transactions;
DROP POLICY IF EXISTS "Auth users categories access" ON categories;
DROP POLICY IF EXISTS "Auth users suppliers access" ON suppliers;
DROP POLICY IF EXISTS "Auth users purchases access" ON purchases;
DROP POLICY IF EXISTS "Auth users purchase_items access" ON purchase_items;
DROP POLICY IF EXISTS "Auth users notifications access" ON notifications;
DROP POLICY IF EXISTS "Auth users settings access" ON app_settings;
DROP POLICY IF EXISTS "Profiles select policy" ON profiles;
DROP POLICY IF EXISTS "Profiles update policy" ON profiles;

-- Create RLS policies for Authenticated Users only
CREATE POLICY "Auth users farmers access" ON farmers FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users products access" ON products FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users batches access" ON product_batches FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users bills select" ON bills FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users bill_items select" ON bill_items FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users movements select" ON stock_movements FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users payments select" ON payments FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users credit select" ON credit_transactions FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users categories access" ON categories FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users suppliers access" ON suppliers FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users purchases access" ON purchases FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users purchase_items access" ON purchase_items FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users notifications access" ON notifications FOR ALL USING (auth.role() = 'authenticated');
CREATE POLICY "Auth users settings access" ON app_settings FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Profiles select policy" ON profiles FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Profiles update policy" ON profiles FOR UPDATE USING (auth.uid() = id);

-- Grant table & sequence privileges so RLS policies take effect cleanly
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated, anon;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, anon;

-- ALL Anonymous read access policies REMOVED to protect internal ERP data


-- 8. TRANSACTIONAL BILLING RPC FUNCTION (create_agromart_bill)
-- Hardened: Proportional Pre-Tax Invoice Discount over Net Subtotal with Residual Handling, Separate CGST/SGST Accumulators, Strict Payment & Null-Safe Farmer Credit
CREATE OR REPLACE FUNCTION create_agromart_bill(
    p_farmer_id BIGINT,
    p_farmer_name TEXT,
    p_farmer_mobile TEXT,
    p_discount_amount NUMERIC,
    p_paid_amount NUMERIC,
    p_cash_amount NUMERIC,
    p_upi_amount NUMERIC,
    p_payment_method TEXT,
    p_due_date TIMESTAMPTZ,
    p_notes TEXT,
    p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_invoice_num TEXT;
    v_year INT;
    v_bill_id BIGINT;
    v_farmer farmers%ROWTYPE;
    v_farmer_pending NUMERIC := 0.0;
    v_farmer_limit NUMERIC := 50000.0;
    v_item JSONB;
    v_product_id BIGINT;
    v_requested_qty INT;
    v_unit_price NUMERIC;
    v_item_disc NUMERIC;
    v_gross_subtotal NUMERIC := 0.0;
    v_total_item_discounts NUMERIC := 0.0;
    v_net_before_inv_disc_subtotal NUMERIC := 0.0;
    v_inv_discount NUMERIC := 0.0;
    v_inv_disc_rem NUMERIC := 0.0;
    v_net_rem NUMERIC := 0.0;
    v_product products%ROWTYPE;
    v_batch product_batches%ROWTYPE;
    v_available_stock INT;
    v_alloc_qty INT;
    v_rem_qty INT;
    
    -- Exact accumulators from rounded bill_items
    v_item_discounts_total NUMERIC := 0.0;
    v_inv_discounts_total NUMERIC := 0.0;
    v_taxable_subtotal NUMERIC := 0.0;
    v_cgst_total NUMERIC := 0.0;
    v_sgst_total NUMERIC := 0.0;
    v_gst_total NUMERIC := 0.0;
    v_grand_total NUMERIC := 0.0;
    v_pending NUMERIC := 0.0;
    v_total_paid NUMERIC := 0.0;
    v_cash_paid NUMERIC := 0.0;
    v_upi_paid NUMERIC := 0.0;
    v_payment_status TEXT;
    
    -- Line item & batch variables
    v_item_gross NUMERIC;
    v_item_disc_rem NUMERIC;
    v_item_qty_rem INT;
    v_item_disc_alloc NUMERIC;
    v_item_net_before_inv NUMERIC;
    v_inv_disc_share NUMERIC;
    v_alloc_taxable NUMERIC;
    v_alloc_gst NUMERIC;
    v_alloc_cgst NUMERIC;
    v_alloc_sgst NUMERIC;
    v_alloc_total NUMERIC;
    v_pay_no TEXT;
BEGIN
    -- A. AUTHENTICATION CHECK
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required to create a bill';
    END IF;

    -- B. PAYLOAD & FINANCIAL VALIDATION
    IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'Cannot generate empty bill. Please add at least one item.';
    END IF;

    v_inv_discount := ROUND(COALESCE(p_discount_amount, 0.0), 2);
    IF v_inv_discount < 0 THEN
        RAISE EXCEPTION 'Invoice discount amount cannot be negative.';
    END IF;

    v_cash_paid := ROUND(COALESCE(p_cash_amount, 0.0), 2);
    v_upi_paid := ROUND(COALESCE(p_upi_amount, 0.0), 2);

    IF COALESCE(p_paid_amount, 0) < 0 OR v_cash_paid < 0 OR v_upi_paid < 0 THEN
        RAISE EXCEPTION 'Payment amounts cannot be negative.';
    END IF;

    -- Component Payment Validation (No conflicting payment numbers)
    IF v_cash_paid > 0 OR v_upi_paid > 0 THEN
        v_total_paid := v_cash_paid + v_upi_paid;
        IF COALESCE(p_paid_amount, 0) > 0 AND ROUND(p_paid_amount, 2) != v_total_paid THEN
            RAISE EXCEPTION 'Conflicting paid amount (₹%) and split cash/UPI payment total (₹%).', ROUND(p_paid_amount, 2), v_total_paid;
        END IF;
    ELSE
        v_total_paid := ROUND(COALESCE(p_paid_amount, 0.0), 2);
    END IF;

    -- C. CONCURRENCY-SAFE INVOICE NUMBER GENERATION
    v_year := EXTRACT(YEAR FROM NOW());
    v_invoice_num := 'AGM-' || v_year || '-' || LPAD(nextval('invoice_number_seq')::TEXT, 5, '0');

    -- D. VALIDATE FARMER IF SPECIFIED
    IF p_farmer_id IS NOT NULL THEN
        SELECT * INTO v_farmer FROM farmers WHERE id = p_farmer_id FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Farmer ID % not found', p_farmer_id;
        END IF;
        v_farmer_pending := COALESCE(v_farmer.pending_credit, 0.0);
        v_farmer_limit := COALESCE(v_farmer.credit_limit, 50000.0);
    END IF;

    -- E. PRE-PASS: VALIDATE PRODUCTS, AUTHORITATIVE PRICES, ITEM DISCOUNTS & NET SUBTOTAL BASE
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_product_id := (v_item->>'product_id')::BIGINT;
        v_requested_qty := (v_item->>'quantity')::INT;
        v_item_disc := ROUND(COALESCE((v_item->>'discount_amount')::NUMERIC, 0.0), 2);

        IF v_requested_qty IS NULL OR v_requested_qty <= 0 THEN
            RAISE EXCEPTION 'Quantity must be greater than zero for product ID %', v_product_id;
        END IF;

        IF v_item_disc < 0 THEN
            RAISE EXCEPTION 'Item discount cannot be negative for product ID %', v_product_id;
        END IF;

        SELECT * INTO v_product FROM products WHERE id = v_product_id FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Product ID % not found', v_product_id;
        END IF;

        IF v_product.status != 'Active' THEN
            RAISE EXCEPTION 'Product % is currently inactive and cannot be sold.', v_product.name;
        END IF;

        -- Authoritative price check strictly from DB
        v_unit_price := v_product.selling_price;
        v_item_gross := v_requested_qty * v_unit_price;

        IF v_item_disc > v_item_gross THEN
            RAISE EXCEPTION 'Item discount (₹%) cannot exceed total item gross price (₹%) for product %', v_item_disc, v_item_gross, v_product.name;
        END IF;

        -- Revalidate available non-expired stock from product_batches (Authoritative Stock Source of Truth)
        SELECT COALESCE(SUM(current_quantity), 0) INTO v_available_stock 
        FROM product_batches 
        WHERE product_id = v_product_id 
          AND current_quantity > 0 
          AND (expiry_date IS NULL OR expiry_date >= CURRENT_DATE);

        IF v_available_stock < v_requested_qty THEN
            RAISE EXCEPTION 'Insufficient non-expired stock for product %. Available: %, Requested: %', v_product.name, v_available_stock, v_requested_qty;
        END IF;

        v_gross_subtotal := v_gross_subtotal + v_item_gross;
        v_total_item_discounts := v_total_item_discounts + v_item_disc;
    END LOOP;

    v_net_before_inv_disc_subtotal := v_gross_subtotal - v_total_item_discounts;

    IF v_inv_discount > v_net_before_inv_disc_subtotal THEN
        RAISE EXCEPTION 'Invoice discount (₹%) cannot exceed net subtotal after item discounts (₹%).', v_inv_discount, v_net_before_inv_disc_subtotal;
    END IF;

    v_inv_disc_rem := v_inv_discount;
    v_net_rem := v_net_before_inv_disc_subtotal;

    -- Create Bill header
    INSERT INTO bills (
        invoice_number, farmer_id, farmer_name, farmer_mobile,
        subtotal, taxable_amount, gst_amount, cgst, sgst, igst,
        discount_amount, grand_total, paid_amount, pending_amount,
        payment_method, payment_status, due_date, notes, created_by
    ) VALUES (
        v_invoice_num, p_farmer_id, COALESCE(v_farmer.name, p_farmer_name, 'Walk-in Customer'),
        COALESCE(v_farmer.mobile, p_farmer_mobile), 0, 0, 0, 0, 0, 0,
        0, 0, v_total_paid, 0,
        COALESCE(p_payment_method, 'Cash'), 'Paid', p_due_date, p_notes, v_user_id
    ) RETURNING id INTO v_bill_id;

    -- F. FEFO BATCH ALLOCATION & PROPORTIONAL INVOICE DISCOUNT WITH EXACT RESIDUAL HANDLERS
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_product_id := (v_item->>'product_id')::BIGINT;
        v_requested_qty := (v_item->>'quantity')::INT;
        v_item_disc := ROUND(COALESCE((v_item->>'discount_amount')::NUMERIC, 0.0), 2);

        SELECT * INTO v_product FROM products WHERE id = v_product_id;
        v_unit_price := v_product.selling_price;
        v_rem_qty := v_requested_qty;
        v_item_disc_rem := v_item_disc;
        v_item_qty_rem := v_requested_qty;

        -- FEFO Allocation with ROW LOCKING (FOR UPDATE)
        FOR v_batch IN 
            SELECT * FROM product_batches 
            WHERE product_id = v_product_id 
              AND current_quantity > 0 
              AND (expiry_date IS NULL OR expiry_date >= CURRENT_DATE)
            ORDER BY expiry_date ASC NULLS LAST
            FOR UPDATE
        LOOP
            IF v_rem_qty <= 0 THEN EXIT; END IF;

            v_alloc_qty := LEAST(v_batch.current_quantity, v_rem_qty);
            
            -- Deduct stock safely from product_batches
            UPDATE product_batches SET current_quantity = current_quantity - v_alloc_qty WHERE id = v_batch.id;
            v_rem_qty := v_rem_qty - v_alloc_qty;

            -- Record Stock Movement as SALE
            INSERT INTO stock_movements (product_id, batch_id, movement_type, quantity, reference_type, reference_id, notes)
            VALUES (v_product_id, v_batch.id, 'SALE', v_alloc_qty, 'BILL', v_invoice_num, 'FEFO Sale Batch ' || v_batch.batch_number);

            v_item_gross := v_alloc_qty * v_unit_price;

            -- Exact Item Discount Allocation with Residual Handling
            IF v_alloc_qty = v_item_qty_rem THEN
                v_item_disc_alloc := v_item_disc_rem;
            ELSE
                v_item_disc_alloc := ROUND(v_item_disc * (v_alloc_qty::NUMERIC / v_requested_qty::NUMERIC), 2);
                v_item_disc_rem := v_item_disc_rem - v_item_disc_alloc;
                v_item_qty_rem := v_item_qty_rem - v_alloc_qty;
            END IF;

            v_item_net_before_inv := v_item_gross - v_item_disc_alloc;

            -- Exact Invoice Discount Share with Residual Handling
            IF v_net_rem > 0 AND v_item_net_before_inv = v_net_rem THEN
                v_inv_disc_share := v_inv_disc_rem;
            ELSIF v_net_before_inv_disc_subtotal > 0 THEN
                v_inv_disc_share := ROUND(v_inv_discount * (v_item_net_before_inv / v_net_before_inv_disc_subtotal), 2);
                IF v_inv_disc_share > v_inv_disc_rem THEN
                    v_inv_disc_share := v_inv_disc_rem;
                END IF;
                v_inv_disc_rem := v_inv_disc_rem - v_inv_disc_share;
                v_net_rem := v_net_rem - v_item_net_before_inv;
            ELSE
                v_inv_disc_share := 0.0;
            END IF;

            -- Final Taxable Amount after exact item discount & proportional invoice discount
            v_alloc_taxable := v_item_net_before_inv - v_inv_disc_share;
            IF v_alloc_taxable < 0 THEN
                RAISE EXCEPTION 'Taxable amount cannot be negative for product %', v_product.name;
            END IF;

            v_alloc_gst := ROUND(v_alloc_taxable * (v_product.gst_percent / 100.0), 2);
            v_alloc_cgst := ROUND(v_alloc_gst / 2.0, 2);
            v_alloc_sgst := v_alloc_gst - v_alloc_cgst; -- Exact split matching gst_amount
            v_alloc_total := v_alloc_taxable + v_alloc_gst;

            -- Accumulate exact 2-decimal rounded header totals
            v_item_discounts_total := v_item_discounts_total + v_item_disc_alloc;
            v_inv_discounts_total := v_inv_discounts_total + v_inv_disc_share;
            v_taxable_subtotal := v_taxable_subtotal + v_alloc_taxable;
            v_cgst_total := v_cgst_total + v_alloc_cgst;
            v_sgst_total := v_sgst_total + v_alloc_sgst;
            v_gst_total := v_cgst_total + v_sgst_total;
            v_grand_total := v_grand_total + v_alloc_total;

            -- Insert Bill Item with exact snapshot
            INSERT INTO bill_items (
                bill_id, product_id, batch_id, product_name, batch_number, unit, hsn_code,
                quantity, unit_price, rate, gst_percent, discount_amount, taxable_amount,
                gst_amount, cgst, sgst, igst, total_amount
            ) VALUES (
                v_bill_id, v_product_id, v_batch.id, v_product.name, v_batch.batch_number,
                COALESCE(v_product.unit, 'Bags'), COALESCE(v_product.hsn_code, '3105'),
                v_alloc_qty, v_unit_price, v_unit_price, v_product.gst_percent,
                (v_item_disc_alloc + v_inv_disc_share),
                v_alloc_taxable, v_alloc_gst, v_alloc_cgst, v_alloc_sgst, 0.0, v_alloc_total
            );
        END LOOP;

        IF v_rem_qty > 0 THEN
            RAISE EXCEPTION 'Allocation failed: Could not fulfill requested stock for product %', v_product.name;
        END IF;

        -- Update derived total_stock cache on product
        UPDATE products SET total_stock = (
            SELECT COALESCE(SUM(current_quantity), 0) 
            FROM product_batches 
            WHERE product_id = v_product_id 
              AND (expiry_date IS NULL OR expiry_date >= CURRENT_DATE)
        ) WHERE id = v_product_id;

    END LOOP;

    -- G. GRAND TOTAL & CREDIT / DUE DATE VALIDATION
    IF v_total_paid > v_grand_total THEN
        RAISE EXCEPTION 'Paid amount (₹%) cannot exceed grand total (₹%).', v_total_paid, v_grand_total;
    END IF;

    v_pending := GREATEST(0.0, v_grand_total - v_total_paid);

    IF v_pending > 0 THEN
        IF p_farmer_id IS NULL THEN
            RAISE EXCEPTION 'Farmer profile required for credit sales. Anonymous credit sales are not allowed.';
        END IF;

        IF p_due_date IS NULL THEN
            RAISE EXCEPTION 'Due date is required for credit sales.';
        END IF;

        IF (v_farmer_pending + v_pending) > v_farmer_limit THEN
            RAISE EXCEPTION 'Credit limit exceeded for farmer %. Limit: ₹%, Current Pending: ₹%, Requested Credit: ₹%', 
                            v_farmer.name, v_farmer_limit, v_farmer_pending, v_pending;
        END IF;

        v_payment_status := CASE WHEN v_total_paid > 0 THEN 'Partial' ELSE 'Credit' END;
    ELSE
        v_payment_status := 'Paid';
    END IF;

    -- Update Bill Header with exact accumulated totals:
    -- SUM(bill_items.taxable_amount) = bills.taxable_amount
    -- SUM(bill_items.cgst) = bills.cgst
    -- SUM(bill_items.sgst) = bills.sgst
    -- SUM(bill_items.gst_amount) = bills.gst_amount
    -- SUM(bill_items.total_amount) = bills.grand_total
    UPDATE bills SET 
        subtotal = v_gross_subtotal,
        discount_amount = (v_item_discounts_total + v_inv_discounts_total),
        taxable_amount = v_taxable_subtotal,
        gst_amount = v_gst_total,
        cgst = v_cgst_total,
        sgst = v_sgst_total,
        grand_total = v_grand_total,
        pending_amount = v_pending,
        payment_status = v_payment_status
    WHERE id = v_bill_id;

    -- H. RECORD PAYMENTS WITH CONCURRENCY SAFE SEQUENCES AND RECONCILED COMPONENT AMOUNTS
    IF v_cash_paid > 0 THEN
        v_pay_no := 'PAY-' || v_year || '-' || LPAD(nextval('payment_number_seq')::TEXT, 5, '0');
        INSERT INTO payments (payment_number, farmer_id, bill_id, payment_type, amount, payment_method, notes)
        VALUES (v_pay_no, p_farmer_id, v_bill_id, 'BILL_PAYMENT', v_cash_paid, 'Cash', 'Cash Payment on Invoice ' || v_invoice_num);
    END IF;

    IF v_upi_paid > 0 THEN
        v_pay_no := 'PAY-' || v_year || '-' || LPAD(nextval('payment_number_seq')::TEXT, 5, '0');
        INSERT INTO payments (payment_number, farmer_id, bill_id, payment_type, amount, payment_method, notes)
        VALUES (v_pay_no, p_farmer_id, v_bill_id, 'BILL_PAYMENT', v_upi_paid, 'UPI', 'UPI Payment on Invoice ' || v_invoice_num);
    END IF;

    IF v_cash_paid = 0 AND v_upi_paid = 0 AND v_total_paid > 0 THEN
        v_pay_no := 'PAY-' || v_year || '-' || LPAD(nextval('payment_number_seq')::TEXT, 5, '0');
        INSERT INTO payments (payment_number, farmer_id, bill_id, payment_type, amount, payment_method, notes)
        VALUES (v_pay_no, p_farmer_id, v_bill_id, 'BILL_PAYMENT', v_total_paid, COALESCE(p_payment_method, 'Cash'), 'Payment on Invoice ' || v_invoice_num);
    END IF;

    -- I. NULL-SAFE CREDIT LEDGER UPDATE
    IF p_farmer_id IS NOT NULL AND v_pending > 0 THEN
        UPDATE farmers SET pending_credit = COALESCE(pending_credit, 0.0) + v_pending WHERE id = p_farmer_id;
        INSERT INTO credit_transactions (farmer_id, bill_id, transaction_type, amount, balance_after, notes)
        VALUES (p_farmer_id, v_bill_id, 'DEBIT', v_pending, (SELECT pending_credit FROM farmers WHERE id = p_farmer_id), 'Credit sale on Invoice ' || v_invoice_num);
    END IF;

    RETURN jsonb_build_object(
        'id', v_bill_id,
        'invoice_number', v_invoice_num,
        'grand_total', v_grand_total,
        'paid_amount', v_total_paid,
        'pending_amount', v_pending,
        'payment_status', v_payment_status
    );
END;
$$;

-- Revoke execute from PUBLIC and anon, grant strictly to authenticated
REVOKE EXECUTE ON FUNCTION create_agromart_bill(BIGINT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TIMESTAMPTZ, TEXT, JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION create_agromart_bill(BIGINT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TIMESTAMPTZ, TEXT, JSONB) TO authenticated;


-- 9. TRANSACTIONAL PURCHASE RPC FUNCTION (create_agromart_purchase)
CREATE OR REPLACE FUNCTION create_agromart_purchase(
    p_supplier_id BIGINT,
    p_supplier_name TEXT,
    p_supplier_mobile TEXT,
    p_discount_amount NUMERIC,
    p_paid_amount NUMERIC,
    p_cash_amount NUMERIC,
    p_upi_amount NUMERIC,
    p_bank_amount NUMERIC,
    p_payment_method TEXT,
    p_notes TEXT,
    p_items JSONB
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_purchase_num TEXT;
    v_year INT;
    v_purchase_id BIGINT;
    v_supplier suppliers%ROWTYPE;
    v_item JSONB;
    v_product_id BIGINT;
    v_requested_qty INT;
    v_purchase_rate NUMERIC;
    v_item_disc NUMERIC;
    v_gst_pct NUMERIC;
    v_batch_no TEXT;
    v_mfg_date DATE;
    v_expiry_date DATE;
    
    v_gross_subtotal NUMERIC := 0.0;
    v_gst_total NUMERIC := 0.0;
    v_grand_total NUMERIC := 0.0;
    v_total_paid NUMERIC := 0.0;
    v_pending NUMERIC := 0.0;
    v_payment_status TEXT;
    
    v_product products%ROWTYPE;
    v_batch_id BIGINT;
    v_item_gross NUMERIC;
    v_item_taxable NUMERIC;
    v_item_gst NUMERIC;
    v_item_total NUMERIC;
    v_pay_no TEXT;
BEGIN
    -- A. AUTHENTICATION CHECK
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required to create a purchase record.';
    END IF;

    -- B. PAYLOAD VALIDATION
    IF p_items IS NULL OR jsonb_array_length(p_items) = 0 THEN
        RAISE EXCEPTION 'Cannot create empty purchase. Please add at least one product item.';
    END IF;

    IF COALESCE(p_paid_amount, 0) < 0 THEN
        RAISE EXCEPTION 'Paid amount cannot be negative.';
    END IF;

    v_total_paid := ROUND(COALESCE(p_paid_amount, 0.0), 2);

    -- C. CONCURRENCY-SAFE PURCHASE NUMBER GENERATION
    v_year := EXTRACT(YEAR FROM NOW());
    v_purchase_num := 'PUR-' || v_year || '-' || LPAD(nextval('purchase_number_seq')::TEXT, 5, '0');

    -- D. VALIDATE SUPPLIER IF SPECIFIED
    IF p_supplier_id IS NOT NULL THEN
        SELECT * INTO v_supplier FROM suppliers WHERE id = p_supplier_id FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Supplier ID % not found', p_supplier_id;
        END IF;
    END IF;

    -- E. PRE-PASS: VALIDATE PRODUCTS, QUANTITIES, PRICES & DATES
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_product_id := (v_item->>'product_id')::BIGINT;
        v_requested_qty := (v_item->>'quantity')::INT;
        v_purchase_rate := ROUND(COALESCE((v_item->>'purchase_price')::NUMERIC, (v_item->>'purchase_rate')::NUMERIC, 0.0), 2);
        v_gst_pct := COALESCE((v_item->>'gst_percent')::NUMERIC, (v_item->>'gst_rate')::NUMERIC, 5.0);
        v_item_disc := ROUND(COALESCE((v_item->>'discount')::NUMERIC, (v_item->>'item_discount')::NUMERIC, 0.0), 2);
        v_mfg_date := CASE WHEN (v_item->>'manufacturing_date') IS NOT NULL AND (v_item->>'manufacturing_date') != '' THEN (v_item->>'manufacturing_date')::DATE ELSE NULL END;
        v_expiry_date := CASE WHEN (v_item->>'expiry_date') IS NOT NULL AND (v_item->>'expiry_date') != '' THEN (v_item->>'expiry_date')::DATE ELSE NULL END;

        IF v_requested_qty IS NULL OR v_requested_qty <= 0 THEN
            RAISE EXCEPTION 'Purchase quantity must be greater than zero for product ID %', v_product_id;
        END IF;

        IF v_purchase_rate < 0 THEN
            RAISE EXCEPTION 'Purchase price cannot be negative for product ID %', v_product_id;
        END IF;

        IF v_gst_pct < 0 OR v_gst_pct > 100 THEN
            RAISE EXCEPTION 'GST percent must be between 0 and 100 for product ID %', v_product_id;
        END IF;

        SELECT * INTO v_product FROM products WHERE id = v_product_id FOR UPDATE;
        IF NOT FOUND THEN
            RAISE EXCEPTION 'Product ID % not found', v_product_id;
        END IF;

        v_item_gross := v_requested_qty * v_purchase_rate;
        IF v_item_disc > v_item_gross THEN
            RAISE EXCEPTION 'Item discount (₹%) cannot exceed line total (₹%) for product %', v_item_disc, v_item_gross, v_product.name;
        END IF;

        IF v_expiry_date IS NOT NULL AND v_expiry_date < CURRENT_DATE THEN
            RAISE EXCEPTION 'Expiry date (%) cannot be in the past for product %', v_expiry_date, v_product.name;
        END IF;

        IF v_mfg_date IS NOT NULL AND v_expiry_date IS NOT NULL AND v_mfg_date > v_expiry_date THEN
            RAISE EXCEPTION 'Manufacturing date (%) cannot be after expiry date (%) for product %', v_mfg_date, v_expiry_date, v_product.name;
        END IF;

        v_item_taxable := v_item_gross - v_item_disc;
        v_item_gst := ROUND(v_item_taxable * (v_gst_pct / 100.0), 2);
        v_item_total := v_item_taxable + v_item_gst;

        v_gross_subtotal := v_gross_subtotal + v_item_taxable;
        v_gst_total := v_gst_total + v_item_gst;
        v_grand_total := v_grand_total + v_item_total;
    END LOOP;

    IF v_total_paid > v_grand_total THEN
        RAISE EXCEPTION 'Paid amount (₹%) cannot exceed purchase grand total (₹%).', v_total_paid, v_grand_total;
    END IF;

    v_pending := GREATEST(0.0, v_grand_total - v_total_paid);

    v_payment_status := CASE 
        WHEN v_total_paid >= v_grand_total THEN 'Paid'
        WHEN v_total_paid > 0 THEN 'Partially Paid'
        ELSE 'Pending'
    END;

    -- F. CREATE PURCHASE HEADER
    INSERT INTO purchases (
        purchase_number, supplier_id, supplier_name,
        subtotal, gst_amount, grand_total, paid_amount, pending_amount,
        payment_status, notes, created_at
    ) VALUES (
        v_purchase_num, p_supplier_id, COALESCE(v_supplier.name, p_supplier_name, 'Unknown Supplier'),
        v_gross_subtotal, v_gst_total, v_grand_total, v_total_paid, v_pending,
        v_payment_status, p_notes, NOW()
    ) RETURNING id INTO v_purchase_id;

    -- G. PROCESS BATCHES, STOCK MOVEMENT & PURCHASE ITEMS
    FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
    LOOP
        v_product_id := (v_item->>'product_id')::BIGINT;
        v_requested_qty := (v_item->>'quantity')::INT;
        v_purchase_rate := ROUND(COALESCE((v_item->>'purchase_price')::NUMERIC, (v_item->>'purchase_rate')::NUMERIC, 0.0), 2);
        v_gst_pct := COALESCE((v_item->>'gst_percent')::NUMERIC, (v_item->>'gst_rate')::NUMERIC, 5.0);
        v_item_disc := ROUND(COALESCE((v_item->>'discount')::NUMERIC, (v_item->>'item_discount')::NUMERIC, 0.0), 2);
        v_batch_no := COALESCE(v_item->>'batch_number', 'BT-' || EXTRACT(EPOCH FROM NOW())::INT);
        v_mfg_date := CASE WHEN (v_item->>'manufacturing_date') IS NOT NULL AND (v_item->>'manufacturing_date') != '' THEN (v_item->>'manufacturing_date')::DATE ELSE NULL END;
        v_expiry_date := CASE WHEN (v_item->>'expiry_date') IS NOT NULL AND (v_item->>'expiry_date') != '' THEN (v_item->>'expiry_date')::DATE ELSE NULL END;

        SELECT * INTO v_product FROM products WHERE id = v_product_id;

        v_item_gross := v_requested_qty * v_purchase_rate;
        v_item_taxable := v_item_gross - v_item_disc;
        v_item_gst := ROUND(v_item_taxable * (v_gst_pct / 100.0), 2);
        v_item_total := v_item_taxable + v_item_gst;

        -- Create or update batch (Upsert on unique_product_batch)
        SELECT id INTO v_batch_id FROM product_batches WHERE product_id = v_product_id AND batch_number = v_batch_no;

        IF v_batch_id IS NOT NULL THEN
            UPDATE product_batches SET
                current_quantity = current_quantity + v_requested_qty,
                purchase_price = v_purchase_rate
            WHERE id = v_batch_id;
        ELSE
            INSERT INTO product_batches (
                product_id, supplier_id, batch_number, mfg_date, expiry_date,
                initial_quantity, current_quantity, purchase_price, selling_price
            ) VALUES (
                v_product_id, p_supplier_id, v_batch_no, v_mfg_date, v_expiry_date,
                v_requested_qty, v_requested_qty, v_purchase_rate, v_product.selling_price
            ) RETURNING id INTO v_batch_id;
        END IF;

        -- Record Purchase Item
        INSERT INTO purchase_items (
            purchase_id, product_id, batch_id, quantity, purchase_price, gst_percent,
            taxable_amount, gst_amount, total_amount
        ) VALUES (
            v_purchase_id, v_product_id, v_batch_id, v_requested_qty, v_purchase_rate, v_gst_pct,
            v_item_taxable, v_item_gst, v_item_total
        );

        -- Record Stock Movement Log (PURCHASE)
        INSERT INTO stock_movements (
            product_id, batch_id, movement_type, quantity, reference_type, reference_id, notes
        ) VALUES (
            v_product_id, v_batch_id, 'PURCHASE', v_requested_qty, 'PURCHASE', v_purchase_num, 'Purchase Order ' || v_purchase_num
        );

        -- Update product purchase_price (Latest Purchase Price) and total_stock summary
        UPDATE products SET
            purchase_price = v_purchase_rate,
            total_stock = (
                SELECT COALESCE(SUM(current_quantity), 0)
                FROM product_batches
                WHERE product_id = v_product_id
                  AND (expiry_date IS NULL OR expiry_date >= CURRENT_DATE)
            )
        WHERE id = v_product_id;
    END LOOP;

    -- H. PAYMENTS & SUPPLIER PAYABLE UPDATE
    IF v_total_paid > 0 THEN
        v_pay_no := 'PAY-SUP-' || v_year || '-' || LPAD(nextval('payment_number_seq')::TEXT, 5, '0');
        INSERT INTO payments (payment_number, supplier_id, purchase_id, payment_type, amount, payment_method, notes)
        VALUES (v_pay_no, p_supplier_id, v_purchase_id, 'SUPPLIER_PAYMENT', v_total_paid, COALESCE(p_payment_method, 'Bank Transfer'), 'Payment for Purchase ' || v_purchase_num);
    END IF;

    IF p_supplier_id IS NOT NULL THEN
        UPDATE suppliers SET
            total_purchases = COALESCE(total_purchases, 0.0) + v_grand_total,
            pending_payment = COALESCE(pending_payment, 0.0) + v_pending,
            pending_payable = COALESCE(pending_payable, 0.0) + v_pending
        WHERE id = p_supplier_id;
    END IF;

    RETURN jsonb_build_object(
        'id', v_purchase_id,
        'purchase_number', v_purchase_num,
        'grand_total', v_grand_total,
        'paid_amount', v_total_paid,
        'pending_amount', v_pending,
        'payment_status', v_payment_status
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION create_agromart_purchase(BIGINT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT, JSONB) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION create_agromart_purchase(BIGINT, TEXT, TEXT, NUMERIC, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT, JSONB) TO authenticated;


-- 10. SUPPLIER PAYMENT RPC FUNCTION (record_supplier_payment)
CREATE OR REPLACE FUNCTION record_supplier_payment(
    p_supplier_id BIGINT,
    p_amount NUMERIC,
    p_payment_method TEXT,
    p_notes TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_supplier suppliers%ROWTYPE;
    v_amount NUMERIC;
    v_pay_no TEXT;
    v_year INT;
    v_new_payable NUMERIC;
BEGIN
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required to record supplier payment.';
    END IF;

    v_amount := ROUND(COALESCE(p_amount, 0.0), 2);
    IF v_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero.';
    END IF;

    SELECT * INTO v_supplier FROM suppliers WHERE id = p_supplier_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Supplier ID % not found.', p_supplier_id;
    END IF;

    IF v_amount > COALESCE(v_supplier.pending_payable, v_supplier.pending_payment, 0.0) THEN
        RAISE EXCEPTION 'Payment amount (₹%) cannot exceed pending payable balance (₹%).', v_amount, COALESCE(v_supplier.pending_payable, v_supplier.pending_payment, 0.0);
    END IF;

    UPDATE suppliers SET
        pending_payment = GREATEST(0.0, COALESCE(pending_payment, 0.0) - v_amount),
        pending_payable = GREATEST(0.0, COALESCE(pending_payable, 0.0) - v_amount)
    WHERE id = p_supplier_id
    RETURNING COALESCE(pending_payable, pending_payment, 0.0) INTO v_new_payable;

    v_year := EXTRACT(YEAR FROM NOW());
    v_pay_no := 'PAY-SUP-' || v_year || '-' || LPAD(nextval('payment_number_seq')::TEXT, 5, '0');

    INSERT INTO payments (payment_number, supplier_id, payment_type, amount, payment_method, notes)
    VALUES (v_pay_no, p_supplier_id, 'SUPPLIER_PAYMENT', v_amount, COALESCE(p_payment_method, 'Bank Transfer'), COALESCE(p_notes, 'Supplier balance payment'));

    RETURN jsonb_build_object(
        'supplier_id', p_supplier_id,
        'payment_number', v_pay_no,
        'amount_paid', v_amount,
        'remaining_payable', v_new_payable
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION record_supplier_payment(BIGINT, NUMERIC, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION record_supplier_payment(BIGINT, NUMERIC, TEXT, TEXT) TO authenticated;


-- 11. FARMER CREDIT PAYMENT RPC FUNCTION (record_farmer_payment)
CREATE OR REPLACE FUNCTION record_farmer_payment(
    p_farmer_id BIGINT,
    p_amount NUMERIC,
    p_payment_method TEXT,
    p_notes TEXT
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
    v_user_id UUID;
    v_farmer farmers%ROWTYPE;
    v_amount NUMERIC;
    v_pay_no TEXT;
    v_payment_id BIGINT;
    v_year INT;
    v_new_pending NUMERIC;
    v_rem_payment NUMERIC;
    v_bill RECORD;
    v_alloc NUMERIC;
    v_new_bill_paid NUMERIC;
    v_new_bill_pending NUMERIC;
    v_new_bill_status TEXT;
BEGIN
    -- 1. AUTHENTICATION CHECK
    v_user_id := auth.uid();
    IF v_user_id IS NULL THEN
        RAISE EXCEPTION 'Authentication required to record farmer payment.';
    END IF;

    -- 2. VALIDATE AMOUNT
    v_amount := ROUND(COALESCE(p_amount, 0.0), 2);
    IF v_amount <= 0 THEN
        RAISE EXCEPTION 'Payment amount must be greater than zero.';
    END IF;

    -- 3. LOCK FARMER ROW & VALIDATE
    SELECT * INTO v_farmer FROM farmers WHERE id = p_farmer_id FOR UPDATE;
    IF NOT FOUND THEN
        RAISE EXCEPTION 'Farmer ID % not found.', p_farmer_id;
    END IF;

    IF v_amount > COALESCE(v_farmer.pending_credit, 0.0) THEN
        RAISE EXCEPTION 'Payment amount (₹%) cannot exceed farmer pending credit (₹%).', v_amount, COALESCE(v_farmer.pending_credit, 0.0);
    END IF;

    -- 4. CALCULATE NEW PENDING CREDIT
    v_new_pending := GREATEST(0.0, COALESCE(v_farmer.pending_credit, 0.0) - v_amount);

    -- 5. GENERATE CONCURRENCY-SAFE PAYMENT NUMBER
    v_year := EXTRACT(YEAR FROM NOW());
    v_pay_no := 'PAY-FMR-' || v_year || '-' || LPAD(nextval('payment_number_seq')::TEXT, 5, '0');

    -- 6. CREATE PAYMENT RECORD
    INSERT INTO payments (
        payment_number, farmer_id, payment_type, amount, payment_method, notes, created_at
    ) VALUES (
        v_pay_no, p_farmer_id, 'FARMER_CREDIT_REPAYMENT', v_amount, COALESCE(p_payment_method, 'Cash'), COALESCE(p_notes, 'Farmer credit repayment'), NOW()
    ) RETURNING id INTO v_payment_id;

    -- 7. REDUCE FARMER PENDING CREDIT
    UPDATE farmers SET pending_credit = v_new_pending WHERE id = p_farmer_id;

    -- 8. CREATE CREDIT TRANSACTION RECORD
    INSERT INTO credit_transactions (
        farmer_id, payment_id, transaction_type, amount, balance_after, notes, created_at
    ) VALUES (
        p_farmer_id, v_payment_id, 'CREDIT', v_amount, v_new_pending, COALESCE(p_notes, 'Repayment on Receipt ' || v_pay_no), NOW()
    );

    -- 9. FIFO PAYMENT ALLOCATION TO OLDEST PENDING BILLS
    v_rem_payment := v_amount;
    FOR v_bill IN 
        SELECT id, paid_amount, pending_amount, grand_total 
        FROM bills 
        WHERE farmer_id = p_farmer_id AND pending_amount > 0 
        ORDER BY created_at ASC, id ASC 
        FOR UPDATE
    LOOP
        EXIT WHEN v_rem_payment <= 0;

        v_alloc := LEAST(v_rem_payment, v_bill.pending_amount);
        v_new_bill_paid := v_bill.paid_amount + v_alloc;
        v_new_bill_pending := GREATEST(0.0, v_bill.pending_amount - v_alloc);
        v_new_bill_status := CASE WHEN v_new_bill_pending = 0 THEN 'Paid' ELSE 'Partial' END;

        UPDATE bills SET 
            paid_amount = v_new_bill_paid,
            pending_amount = v_new_bill_pending,
            payment_status = v_new_bill_status
        WHERE id = v_bill.id;

        v_rem_payment := v_rem_payment - v_alloc;
    END LOOP;

    RETURN jsonb_build_object(
        'farmer_id', p_farmer_id,
        'payment_number', v_pay_no,
        'amount_paid', v_amount,
        'remaining_pending_credit', v_new_pending
    );
END;
$$;

REVOKE EXECUTE ON FUNCTION record_farmer_payment(BIGINT, NUMERIC, TEXT, TEXT) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION record_farmer_payment(BIGINT, NUMERIC, TEXT, TEXT) TO authenticated;

-- =========================================================================
-- SECURITY PATCH: STRICT SCHEMA & ROLE PERMISSIONS
-- =========================================================================

-- 1. REVOKE ALL PRIVILEGES FROM anon AND PUBLIC
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM anon, PUBLIC;
REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM anon, PUBLIC;

-- 2. MASTER & OPERATIONAL TABLES: GRANT CRUD STRICTLY TO authenticated
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE 
    profiles, 
    farmers, 
    suppliers, 
    categories, 
    products, 
    product_batches, 
    notifications, 
    app_settings 
TO authenticated;

-- 3. TRANSACTIONAL & AUDIT TABLES: GRANT SELECT ONLY TO authenticated (DIRECT WRITES BLOCKED)
GRANT SELECT ON TABLE 
    bills, 
    bill_items, 
    payments, 
    credit_transactions, 
    stock_movements, 
    purchases, 
    purchase_items 
TO authenticated;

-- 4. SEQUENCES: GRANT USAGE AND SELECT STRICTLY TO authenticated
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- HELPER RPC FOR TEST USER EMAIL CONFIRMATION
CREATE OR REPLACE FUNCTION confirm_test_user(p_email TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, auth, pg_temp
AS $$
BEGIN
    UPDATE auth.users 
    SET email_confirmed_at = COALESCE(email_confirmed_at, NOW()), 
        confirmed_at = COALESCE(confirmed_at, NOW())
    WHERE email = p_email;
END;
$$;

REVOKE EXECUTE ON FUNCTION confirm_test_user(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION confirm_test_user(TEXT) TO authenticated, anon;




